#!/usr/bin/env bash

require_deploy_config
set_deploy_hosts

run() {
  if [[ -z "$SHARED_SOURCE" || -z "$SHARED_DESTINATION" ]]; then
    echo "No --shared-source and --shared-destination arguments for shared deployment. Skipping..."
    return
  fi

  authorize_hosts
  authorize_remote_hosts

  remote_deploy_shared "${SHARED_SOURCE}" "${SHARED_DESTINATION}"
}
